### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by DavidEscalante** [neod/FidelityFXOnVideo#1]
I have tried everything in my power to make this work. I have a little prores .mov file that I am trying to use for test this.

But doesnt mater if I build the file from source, or use the .exe Binary, or if I use the source from the .exe binary.

I am always getting this error:
`Unhandled exception. System.ComponentModel.Win32Exception (2): The system cannot find the file specified.`

This is the whole log:
```
Extracting video frames and audio
Unhandled exception. System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Instances.Instance.Start()
   at Instances.Instance.set_Started(Boolean value)
   at Instances.Instance.BlockUntilFinished()
   at Instances.Instance.Finish(ProcessStartInfo startInfo, EventHandler`1 outputHandler)
   at Instances.Instance.Finish(String path, String arguments, EventHandler`1 outputHandler)
   at FFMpegCore.Helpers.FFProbeHelper.VerifyFFProbeExists(FFOptions ffMpegOptions)
   at FFMpegCore.FFProbe.PrepareInstance(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at FFMpegCore.FFProbe.Analyse(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at FidelityFXOnVideo.FidelityFXOnVideo.FfmpegExtract(String videoFullpathFile)
   at FidelityFXOnVideo.Program.Main(String[] args)
```

I have every dependecy installed on the version required, and I am using full paths. It actually creates the "frame" folder besides the . mov file, so seems the file it can't find is not the video or the video location, so no idea what file is not failing to find.

**Comment by DavidEscalante** [comment]
I solved it. Using the path to locate ffmpeg doesn't solve it you have to put all 3 files included in the ffmpeg package on the same location than .exe, then it works.
